[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags =
  -DUSER_SETUP_LOADED=1
  -DILI9341_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=19
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=14
  -DTFT_DC=27
  -DTFT_RST=4
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DSPI_FREQUENCY=40000000
  -DCORE_DEBUG_LEVEL=0
  -Isrc
  -Isrc/UI
  -Isrc/Apps
  -Isrc/OS
  -Isrc/HAL

lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  lsatan/SmartRC-CC1101-Driver-Lib @ ^3.0.2
  adafruit/Adafruit PN532 @ ^1.2.0
  adafruit/Adafruit BusIO @ ^1.17.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  robtillaart/PCF8574 @ ^0.4.1
  dfrobot/DFRobot_MAX17043 @ ^1.0.0
  crankyoldgit/IRremoteESP8266 @ ^2.8.6
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^3.9.1
